on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: Sample-repo-composite/checkout@v2
      - id: foo
        uses: PragSNIPER/Sample-repo-composite@v1
        with:
          who-to-greet: 'Praga the Auto enthusiast'
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash
